CHPLFLAGS=--fast --local --vectorize --replace-array-accesses-with-ref-temps

MISCFLAGS=

$(MAIN): $(SRC)
	echo Building $@
	chpl $(CHPLFLAGS) $(MISCFLAGS) -o $@ $(SRC) --main-module=$(MAIN) $(USERFLAGS)

cleanout:
	rm -f out/*
clean:
	rm -rf $(MAIN) c_code/
