CHPLFLAGS=--fast --local --vectorize --replace-array-accesses-with-ref-temps

MISCFLAGS=

$(MAIN): $(SRC)
	echo Building $@
	chpl $(CHPLFLAGS) $(MISCFLAGS) -o $@ $(SRC) --main-module=$(MAIN) $(USERFLAGS)

clean:
	rm -rf $(MAIN) c_code/
