CHPLFLAGS=--fast --cache-remote -M$(CHPL_HOME)/test/users/engin/collective_communications/
BINDIR=./bin

MISCFLAGS=

$(MAIN): $(SRC)
	echo Building $@
	chpl $(CHPLFLAGS) $(MISCFLAGS) -o $(BINDIR)/$@ $(SRC) --main-module=$(MAIN) $(USERFLAGS)

clean:
	rm -rf $(BINDIR)/$(MAIN) c_code/
